custom form
lara-zeus/qr pull request #37
Opened 2024-09-26 07:43 UTC by do-dyco

2024-09-27 03:14 UTC, yughoz commented
https://github.com/user-attachments/assets/9ee3b66c-7865-4e87-8131-43908c17e3b5

custom logo size and correction

2024-09-27 04:12 UTC, atmonshi commented
thank you @do-dyco and @yughoz 
there is two PRs with similar changes, can we agree on one and close the other :)

2024-09-27 08:08 UTC, yughoz commented
> thank you @do-dyco and @yughoz there is two PRs with similar changes, can we agree on one and close the other :)

Let me know if you need any adjustments!

2024-09-30 09:13 UTC, atmonshi requested changes
thank you so much for the PR, these are small code refactoring

2024-09-30 09:13 UTC, atmonshi commented on src/Facades/Qr.php
> +                            Select::make('correction')
since `correction` is a new option, we need to add it to the `getDefaultOptions` too

2024-09-30 09:13 UTC, atmonshi commented on src/Facades/Qr.php
> +
duplicated empty line :)

2024-09-30 09:13 UTC, atmonshi commented on src/Facades/Qr.php
> +                                ->visible(fn(Get $get) => $get('hasGradient')),
can you revert the code formatting

2024-09-30 09:13 UTC, atmonshi commented on src/Facades/Qr.php
> +                                ->visible(fn(Get $get) => $get('hasEyeColor')),
can you revert the code formatting  and empty line

2024-09-30 09:13 UTC, atmonshi commented on src/Facades/Qr.php
> +                            Select::make('percentage')
also add `percentage` to `getDefaultOptions`

2024-09-30 09:13 UTC, atmonshi commented on src/Facades/Qr.php
> +                        ->content(fn(Get $get) => Qr::render(
code formatting

2024-09-30 09:13 UTC, atmonshi commented on src/Facades/Qr.php
> +        // $maker->errorCorrection('L');
if we added the `percentage` to the default array we dont need this default variable

2024-09-30 09:13 UTC, atmonshi commented on src/Facades/Qr.php
> +            if ($logo instanceof \Illuminate\Http\UploadedFile && filled($logo->getPathName())) {
I am not following this part and why we need it?
if the image loaded from a storage path I dont think we need to upload it again, right?

2024-12-04 06:27 UTC, aSmodeusW commented
@yughoz, @atmonshi  can you tell me how you overcame issue of uploading qr code? i can upload it but when i want to view that image of an qr code in an edit,it says Call to a member function getPathName() on string

2024-12-04 07:20 UTC, yughoz commented
> @yughoz, @atmonshi can you tell me how you overcame issue of uploading qr code? i can upload it but when i want to view that image of an qr code in an edit,it says Call to a member function getPathName() on string

I have updated in my git
just waiting for the PR to be approved

2024-12-22 16:08 UTC, atmonshi commented
fix #39

2024-12-22 16:08 UTC, merged